/* Generated By:JavaCC: Do not edit this line. JavaCCParserTokenManager.java */
package jminusminus;
import java.util.ArrayList;

public class JavaCCParserTokenManager implements JavaCCParserConstants
{
  public  java.io.PrintStream debugStream = System.out;
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x1ffffffffff00L) != 0L)
         {
            jjmatchedKind = 95;
            return 1;
         }
         if ((active1 & 0x20000000L) != 0L)
            return 13;
         if ((active0 & 0x2000000000000000L) != 0L || (active1 & 0x100L) != 0L)
            return 38;
         return -1;
      case 1:
         if ((active0 & 0x6000008000L) != 0L)
            return 1;
         if ((active0 & 0x1ff9fffff7f00L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 95;
               jjmatchedPos = 1;
            }
            return 1;
         }
         return -1;
      case 2:
         if ((active0 & 0xf5dffff37f00L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 95;
               jjmatchedPos = 2;
            }
            return 1;
         }
         if ((active0 & 0x10a00000c0000L) != 0L)
            return 1;
         return -1;
      case 3:
         if ((active0 & 0xeddd8fe36b00L) != 0L)
         {
            jjmatchedKind = 95;
            jjmatchedPos = 3;
            return 1;
         }
         if ((active0 & 0x100270101400L) != 0L)
            return 1;
         return -1;
      case 4:
         if ((active0 & 0x2c5807e32300L) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 95;
               jjmatchedPos = 4;
            }
            return 1;
         }
         if ((active0 & 0xc18588004800L) != 0L)
            return 1;
         return -1;
      case 5:
         if ((active0 & 0xd1800e22300L) != 0L)
         {
            jjmatchedKind = 95;
            jjmatchedPos = 5;
            return 1;
         }
         if ((active0 & 0xa04007010000L) != 0L)
            return 1;
         return -1;
      case 6:
         if ((active0 & 0xc0800820100L) != 0L)
         {
            jjmatchedKind = 95;
            jjmatchedPos = 6;
            return 1;
         }
         if ((active0 & 0x11000602200L) != 0L)
            return 1;
         return -1;
      case 7:
         if ((active0 & 0xc0000820000L) != 0L)
         {
            jjmatchedKind = 95;
            jjmatchedPos = 7;
            return 1;
         }
         if ((active0 & 0x800000100L) != 0L)
            return 1;
         return -1;
      case 8:
         if ((active0 & 0x80000800000L) != 0L)
            return 1;
         if ((active0 & 0x40000020000L) != 0L)
         {
            jjmatchedKind = 95;
            jjmatchedPos = 8;
            return 1;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private final int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private final int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private final int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 57;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x80L);
      case 37:
         jjmatchedKind = 62;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x800L);
      case 38:
         jjmatchedKind = 68;
         return jjMoveStringLiteralDfa1_0(0x80000000000000L, 0x100000L);
      case 40:
         return jjStopAtPos(0, 85);
      case 41:
         return jjStopAtPos(0, 86);
      case 42:
         jjmatchedKind = 60;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x400L);
      case 43:
         jjmatchedKind = 49;
         return jjMoveStringLiteralDfa1_0(0x840000000000000L, 0x0L);
      case 44:
         return jjStopAtPos(0, 92);
      case 45:
         jjmatchedKind = 58;
         return jjMoveStringLiteralDfa1_0(0x8000000000000L, 0x200L);
      case 46:
         return jjStartNfaWithStates_0(0, 93, 13);
      case 47:
         jjmatchedKind = 61;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x100L);
      case 58:
         return jjStopAtPos(0, 94);
      case 59:
         return jjStopAtPos(0, 91);
      case 60:
         jjmatchedKind = 80;
         return jjMoveStringLiteralDfa1_0(0x8100000000000000L, 0x8000L);
      case 61:
         jjmatchedKind = 50;
         return jjMoveStringLiteralDfa1_0(0x10000000000000L, 0x0L);
      case 62:
         jjmatchedKind = 53;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x7003L);
      case 63:
         return jjStopAtPos(0, 70);
      case 91:
         return jjStopAtPos(0, 89);
      case 93:
         return jjStopAtPos(0, 90);
      case 94:
         jjmatchedKind = 67;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x20000L);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x100L, 0x0L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x100000200L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0xe00000c00L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x7000000000L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x3000L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x38000004000L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0xc0000078000L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x100000000000L, 0x0L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x180000L, 0x0L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x1e00000L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x2000000L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x20000c000000L, 0x0L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x1c00030000000L, 0x0L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x40000000L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x80000000L, 0x0L);
      case 123:
         return jjStopAtPos(0, 87);
      case 124:
         jjmatchedKind = 66;
         return jjMoveStringLiteralDfa1_0(0x0L, 0xc0000L);
      case 125:
         return jjStopAtPos(0, 88);
      case 126:
         return jjStopAtPos(0, 69);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private final int jjMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active0 & 0x80000000000000L) != 0L)
            return jjStopAtPos(1, 55);
         break;
      case 43:
         if ((active0 & 0x40000000000000L) != 0L)
            return jjStopAtPos(1, 54);
         break;
      case 45:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStopAtPos(1, 51);
         break;
      case 60:
         if ((active0 & 0x8000000000000000L) != 0L)
         {
            jjmatchedKind = 63;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x8000L);
      case 61:
         if ((active0 & 0x10000000000000L) != 0L)
            return jjStopAtPos(1, 52);
         else if ((active0 & 0x100000000000000L) != 0L)
            return jjStopAtPos(1, 56);
         else if ((active0 & 0x800000000000000L) != 0L)
            return jjStopAtPos(1, 59);
         else if ((active1 & 0x80L) != 0L)
            return jjStopAtPos(1, 71);
         else if ((active1 & 0x100L) != 0L)
            return jjStopAtPos(1, 72);
         else if ((active1 & 0x200L) != 0L)
            return jjStopAtPos(1, 73);
         else if ((active1 & 0x400L) != 0L)
            return jjStopAtPos(1, 74);
         else if ((active1 & 0x800L) != 0L)
            return jjStopAtPos(1, 75);
         else if ((active1 & 0x4000L) != 0L)
            return jjStopAtPos(1, 78);
         else if ((active1 & 0x20000L) != 0L)
            return jjStopAtPos(1, 81);
         else if ((active1 & 0x40000L) != 0L)
            return jjStopAtPos(1, 82);
         else if ((active1 & 0x100000L) != 0L)
            return jjStopAtPos(1, 84);
         break;
      case 62:
         if ((active1 & 0x1L) != 0L)
         {
            jjmatchedKind = 64;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x3002L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x600204000L, active1, 0L);
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0x100L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x1002080000L, active1, 0L);
      case 102:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(1, 15, 1);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0xc00090000400L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x18000000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x1800L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000010000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000060000L, active1, 0L);
      case 111:
         if ((active0 & 0x2000000000L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x124840000200L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000120c00000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x9100000L, active1, 0L);
      case 119:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000000000L, active1, 0L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000L, active1, 0L);
      case 124:
         if ((active1 & 0x80000L) != 0L)
            return jjStopAtPos(1, 83);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
private final int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 61:
         if ((active1 & 0x1000L) != 0L)
            return jjStopAtPos(2, 76);
         else if ((active1 & 0x8000L) != 0L)
            return jjStopAtPos(2, 79);
         break;
      case 62:
         if ((active1 & 0x2L) != 0L)
         {
            jjmatchedKind = 65;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x2000L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000c00L, active1, 0L);
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000L, active1, 0L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000d0400000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x104000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x118800000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x800200L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x40008010000L, active1, 0L);
      case 114:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 41, 1);
         return jjMoveStringLiteralDfa3_0(active0, 0xc00000000000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x200021100L, active1, 0L);
      case 116:
         if ((active0 & 0x40000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x80402002000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x4020000000L, active1, 0L);
      case 119:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(2, 19, 1);
         break;
      case 121:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 48, 1);
         break;
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
private final int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1);
      return 3;
   }
   switch(curChar)
   {
      case 61:
         if ((active1 & 0x2000L) != 0L)
            return jjStopAtPos(3, 77);
         break;
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x19100000000L, active1, 0L);
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000L, active1, 0L);
      case 100:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(3, 30, 1);
         break;
      case 101:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(3, 12, 1);
         else if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(3, 29, 1);
         else if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(3, 33, 1);
         return jjMoveStringLiteralDfa4_0(active0, 0x80008002000L, active1, 0L);
      case 103:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 44, 1);
         break;
      case 107:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000L, active1, 0L);
      case 108:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(3, 20, 1);
         return jjMoveStringLiteralDfa4_0(active0, 0x40081000200L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0xc00000010000L, active1, 0L);
      case 114:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(3, 10, 1);
         break;
      case 115:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(3, 28, 1);
         return jjMoveStringLiteralDfa4_0(active0, 0x4800L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x200804820100L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000L, active1, 0L);
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1);
}
private final int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, 0L);
      return 4;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x620000L);
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000000000L);
      case 101:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(4, 14, 1);
         else if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(4, 31, 1);
         return jjMoveStringLiteralDfa5_0(active0, 0x40000800200L);
      case 104:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(4, 34, 1);
         break;
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x805000000L);
      case 107:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(4, 32, 1);
         break;
      case 108:
         if ((active0 & 0x8000000000L) != 0L)
         {
            jjmatchedKind = 39;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x14000000000L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000L);
      case 114:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(4, 27, 1);
         return jjMoveStringLiteralDfa5_0(active0, 0x80002010100L);
      case 115:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(4, 11, 1);
         break;
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000000L);
      case 119:
         if ((active0 & 0x400000000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, 0L);
}
private final int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, 0L);
      return 5;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x300L);
      case 99:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(5, 24, 1);
         else if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(5, 26, 1);
         return jjMoveStringLiteralDfa6_0(active0, 0x800000L);
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000L);
      case 101:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 38, 1);
         break;
      case 102:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000000000L);
      case 103:
         return jjMoveStringLiteralDfa6_0(active0, 0x200000L);
      case 104:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 45, 1);
         break;
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x11000000000L);
      case 109:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000000L);
      case 110:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(5, 25, 1);
         return jjMoveStringLiteralDfa6_0(active0, 0x800020000L);
      case 115:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 47, 1);
         break;
      case 116:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(5, 16, 1);
         return jjMoveStringLiteralDfa6_0(active0, 0x400000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, 0L);
}
private final int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, 0L);
      return 6;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x80000000000L);
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x20100L);
      case 101:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(6, 21, 1);
         else if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(6, 22, 1);
         return jjMoveStringLiteralDfa7_0(active0, 0x40000000000L);
      case 110:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(6, 9, 1);
         break;
      case 115:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(6, 13, 1);
         break;
      case 116:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 36, 1);
         return jjMoveStringLiteralDfa7_0(active0, 0x800000L);
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000000L);
      case 121:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 40, 1);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0, 0L);
}
private final int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, 0L);
      return 7;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x80000000000L);
      case 101:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(7, 35, 1);
         return jjMoveStringLiteralDfa8_0(active0, 0x820000L);
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0x40000000000L);
      case 116:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(7, 8, 1);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0, 0L);
}
private final int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 100:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(8, 23, 1);
         break;
      case 101:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 43, 1);
         break;
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x20000L);
      case 116:
         return jjMoveStringLiteralDfa9_0(active0, 0x40000000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, 0L);
}
private final int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, 0L);
      return 9;
   }
   switch(curChar)
   {
      case 102:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(9, 17, 1);
         break;
      case 115:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 42, 1);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0, 0L);
}
private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 54;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 6);
                  else if (curChar == 47)
                     jjAddStates(7, 8);
                  else if (curChar == 46)
                     jjCheckNAdd(13);
                  else if (curChar == 34)
                     jjCheckNAddStates(9, 11);
                  else if (curChar == 39)
                     jjAddStates(12, 13);
                  else if (curChar == 36)
                  {
                     if (kind > 95)
                        kind = 95;
                     jjCheckNAdd(1);
                  }
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 99)
                        kind = 99;
                     jjCheckNAddStates(14, 16);
                  }
                  else if (curChar == 48)
                  {
                     if (kind > 99)
                        kind = 99;
                     jjCheckNAdd(50);
                  }
                  break;
               case 38:
                  if (curChar == 42)
                     jjCheckNAddTwoStates(44, 45);
                  else if (curChar == 47)
                     jjCheckNAddStates(17, 19);
                  break;
               case 1:
                  if ((0x3ff001000000000L & l) == 0L)
                     break;
                  if (kind > 95)
                     kind = 95;
                  jjCheckNAdd(1);
                  break;
               case 2:
                  if (curChar == 39)
                     jjAddStates(12, 13);
                  break;
               case 4:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAdd(5);
                  break;
               case 5:
                  if (curChar == 39 && kind > 100)
                     kind = 100;
                  break;
               case 6:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     jjCheckNAdd(5);
                  break;
               case 7:
                  if (curChar == 34)
                     jjCheckNAddStates(9, 11);
                  break;
               case 9:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAddStates(9, 11);
                  break;
               case 10:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddStates(9, 11);
                  break;
               case 11:
                  if (curChar == 34 && kind > 101)
                     kind = 101;
                  break;
               case 12:
                  if (curChar == 46)
                     jjCheckNAdd(13);
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 107)
                     kind = 107;
                  jjCheckNAddStates(20, 22);
                  break;
               case 16:
                  if ((0x280000000000L & l) == 0L)
                     break;
                  if (kind > 107)
                     kind = 107;
                  jjCheckNAddTwoStates(17, 14);
                  break;
               case 17:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 107)
                     kind = 107;
                  jjCheckNAddTwoStates(14, 17);
                  break;
               case 18:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 107)
                     kind = 107;
                  jjCheckNAddTwoStates(14, 18);
                  break;
               case 19:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 6);
                  break;
               case 20:
                  if (curChar != 46)
                     break;
                  if (kind > 107)
                     kind = 107;
                  jjCheckNAddStates(23, 25);
                  break;
               case 21:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 107)
                     kind = 107;
                  jjCheckNAddStates(23, 25);
                  break;
               case 23:
                  if ((0x280000000000L & l) == 0L)
                     break;
                  if (kind > 107)
                     kind = 107;
                  jjCheckNAddTwoStates(24, 14);
                  break;
               case 24:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 107)
                     kind = 107;
                  jjCheckNAddTwoStates(14, 24);
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 107)
                     kind = 107;
                  jjCheckNAddTwoStates(14, 25);
                  break;
               case 26:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(26, 27);
                  break;
               case 28:
                  if ((0x280000000000L & l) == 0L)
                     break;
                  if (kind > 107)
                     kind = 107;
                  jjCheckNAddTwoStates(29, 14);
                  break;
               case 29:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 107)
                     kind = 107;
                  jjCheckNAddTwoStates(14, 29);
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 107)
                     kind = 107;
                  jjCheckNAddTwoStates(14, 30);
                  break;
               case 31:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(26, 28);
                  break;
               case 33:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddTwoStates(34, 14);
                  break;
               case 34:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(14, 34);
                  break;
               case 35:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(14, 35);
                  break;
               case 36:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(20, 36);
                  break;
               case 37:
                  if (curChar == 47)
                     jjAddStates(7, 8);
                  break;
               case 39:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(17, 19);
                  break;
               case 40:
                  if ((0x2400L & l) != 0L && kind > 6)
                     kind = 6;
                  break;
               case 41:
                  if (curChar == 10 && kind > 6)
                     kind = 6;
                  break;
               case 42:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 43:
                  if (curChar == 42)
                     jjCheckNAddTwoStates(44, 45);
                  break;
               case 44:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(44, 45);
                  break;
               case 45:
                  if (curChar == 42)
                     jjCheckNAddStates(29, 31);
                  break;
               case 46:
                  if ((0xffff7bffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(47, 45);
                  break;
               case 47:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(47, 45);
                  break;
               case 48:
                  if (curChar == 47 && kind > 7)
                     kind = 7;
                  break;
               case 49:
                  if (curChar != 48)
                     break;
                  if (kind > 99)
                     kind = 99;
                  jjCheckNAdd(50);
                  break;
               case 51:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 99)
                     kind = 99;
                  jjCheckNAddStates(14, 16);
                  break;
               case 52:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 99)
                     kind = 99;
                  jjCheckNAdd(52);
                  break;
               case 53:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(53, 50);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 0:
               case 1:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 95)
                     kind = 95;
                  jjCheckNAdd(1);
                  break;
               case 3:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 4:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAdd(5);
                  break;
               case 6:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAdd(5);
                  break;
               case 8:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 9:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAddStates(9, 11);
                  break;
               case 10:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(9, 11);
                  break;
               case 14:
                  if ((0x1000000010L & l) != 0L && kind > 107)
                     kind = 107;
                  break;
               case 15:
                  if ((0x2000000020L & l) == 0L)
                     break;
                  if (kind > 107)
                     kind = 107;
                  jjCheckNAddStates(32, 34);
                  break;
               case 22:
                  if ((0x2000000020L & l) == 0L)
                     break;
                  if (kind > 107)
                     kind = 107;
                  jjCheckNAddStates(35, 37);
                  break;
               case 27:
                  if ((0x2000000020L & l) == 0L)
                     break;
                  if (kind > 107)
                     kind = 107;
                  jjCheckNAddStates(38, 40);
                  break;
               case 32:
                  if ((0x2000000020L & l) != 0L)
                     jjCheckNAddStates(41, 43);
                  break;
               case 39:
                  jjAddStates(17, 19);
                  break;
               case 44:
                  jjCheckNAddTwoStates(44, 45);
                  break;
               case 46:
               case 47:
                  jjCheckNAddTwoStates(47, 45);
                  break;
               case 50:
                  if ((0x100000001000L & l) != 0L && kind > 103)
                     kind = 103;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 6:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 10:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(9, 11);
                  break;
               case 39:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(17, 19);
                  break;
               case 44:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(44, 45);
                  break;
               case 46:
               case 47:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(47, 45);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 54 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   20, 26, 31, 14, 32, 27, 36, 38, 43, 8, 10, 11, 3, 6, 52, 53, 
   50, 39, 40, 42, 13, 14, 15, 21, 14, 22, 31, 14, 32, 45, 46, 48, 
   16, 18, 14, 23, 25, 14, 28, 30, 14, 33, 35, 14, 
};
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, 
"\141\142\163\164\162\141\143\164", "\142\157\157\154\145\141\156", "\143\150\141\162", "\143\154\141\163\163", 
"\145\154\163\145", "\145\170\164\145\156\144\163", "\146\141\154\163\145", "\151\146", 
"\151\155\160\157\162\164", "\151\156\163\164\141\156\143\145\157\146", "\151\156\164", "\156\145\167", 
"\156\165\154\154", "\160\141\143\153\141\147\145", "\160\162\151\166\141\164\145", 
"\160\162\157\164\145\143\164\145\144", "\160\165\142\154\151\143", "\162\145\164\165\162\156", 
"\163\164\141\164\151\143", "\163\165\160\145\162", "\164\150\151\163", "\164\162\165\145", 
"\166\157\151\144", "\167\150\151\154\145", "\142\162\145\141\153", "\143\141\163\145", 
"\143\141\164\143\150", "\143\157\156\164\151\156\165\145", "\144\145\146\141\165\154\164", 
"\144\157", "\144\157\165\142\154\145", "\146\151\156\141\154", 
"\146\151\156\141\154\154\171", "\146\157\162", "\151\155\160\154\145\155\145\156\164\163", 
"\151\156\164\145\162\146\141\143\145", "\154\157\156\147", "\163\167\151\164\143\150", "\164\150\162\157\167", 
"\164\150\162\157\167\163", "\164\162\171", "\53", "\75", "\55\55", "\75\75", "\76", "\53\53", "\46\46", 
"\74\75", "\41", "\55", "\53\75", "\52", "\57", "\45", "\74\74", "\76\76", "\76\76\76", 
"\174", "\136", "\46", "\176", "\77", "\41\75", "\57\75", "\55\75", "\52\75", 
"\45\75", "\76\76\75", "\76\76\76\75", "\76\75", "\74\74\75", "\74", "\136\75", 
"\174\75", "\174\174", "\46\75", "\50", "\51", "\173", "\175", "\133", "\135", "\73", 
"\54", "\56", "\72", null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, };
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0xffffffffffffff01L, 0x18b8ffffffffL, 
};
static final long[] jjtoSkip = {
   0xfeL, 0x0L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[54];
private final int[] jjstateSet = new int[108];
protected char curChar;
public JavaCCParserTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}
public JavaCCParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 54; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

public Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100003600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedPos == 0 && jjmatchedKind > 108)
   {
      jjmatchedKind = 108;
   }
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

}
