/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package jminusminus;

public interface JavaCCParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int MULTI_LINE_COMMENT = 7;
  int ABSTRACT = 8;
  int BOOLEAN = 9;
  int CHAR = 10;
  int CLASS = 11;
  int ELSE = 12;
  int EXTENDS = 13;
  int FALSE = 14;
  int IF = 15;
  int IMPORT = 16;
  int INSTANCEOF = 17;
  int INT = 18;
  int NEW = 19;
  int NULL = 20;
  int PACKAGE = 21;
  int PRIVATE = 22;
  int PROTECTED = 23;
  int PUBLIC = 24;
  int RETURN = 25;
  int STATIC = 26;
  int SUPER = 27;
  int THIS = 28;
  int TRUE = 29;
  int VOID = 30;
  int WHILE = 31;
  int BREAK = 32;
  int CASE = 33;
  int CATCH = 34;
  int CONTINUE = 35;
  int Default = 36;
  int DO = 37;
  int DOUBLE = 38;
  int FINAL = 39;
  int FINALLY = 40;
  int FOR = 41;
  int IMPLEMENTS = 42;
  int INTERFACE = 43;
  int LONG = 44;
  int SWITCH = 45;
  int THROW = 46;
  int THROWS = 47;
  int TRY = 48;
  int PLUS = 49;
  int ASSIGN = 50;
  int DEC = 51;
  int EQUAL = 52;
  int GT = 53;
  int INC = 54;
  int LAND = 55;
  int LE = 56;
  int LNOT = 57;
  int MINUS = 58;
  int PLUS_ASSIGN = 59;
  int STAR = 60;
  int DIV = 61;
  int REM = 62;
  int SHL = 63;
  int SHR = 64;
  int USHR = 65;
  int OR = 66;
  int XOR = 67;
  int AND = 68;
  int NOT = 69;
  int QUES = 70;
  int NOT_ASSIGN = 71;
  int DIV_ASSIGN = 72;
  int MIN_ASSIGN = 73;
  int STAR_ASSIGN = 74;
  int REM_ASSIGN = 75;
  int SHR_ASSIGN = 76;
  int USHR_ASSIGN = 77;
  int GE = 78;
  int SHL_ASSIGN = 79;
  int LT = 80;
  int XOR_ASSIGN = 81;
  int OR_ASSIGN = 82;
  int LOR = 83;
  int AND_ASSIGN = 84;
  int LPAREN = 85;
  int RPAREN = 86;
  int LCURLY = 87;
  int RCURLY = 88;
  int LBRACK = 89;
  int RBRACK = 90;
  int SEMI = 91;
  int COMMA = 92;
  int DOT = 93;
  int COLON = 94;
  int IDENTIFIER = 95;
  int LETTER = 96;
  int DIGIT = 97;
  int NON_ZERO_DIGIT = 98;
  int INT_LITERAL = 99;
  int CHAR_LITERAL = 100;
  int STRING_LITERAL = 101;
  int ESC = 102;
  int LONG_LITERAL = 103;
  int DIGITS = 104;
  int EXPONENT = 105;
  int SUFFIX = 106;
  int DOUBLE_LITERAL = 107;
  int ERROR = 108;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"abstract\"",
    "\"boolean\"",
    "\"char\"",
    "\"class\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"if\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"super\"",
    "\"this\"",
    "\"true\"",
    "\"void\"",
    "\"while\"",
    "\"break\"",
    "\"case\"",
    "\"catch\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"final\"",
    "\"finally\"",
    "\"for\"",
    "\"implements\"",
    "\"interface\"",
    "\"long\"",
    "\"switch\"",
    "\"throw\"",
    "\"throws\"",
    "\"try\"",
    "\"+\"",
    "\"=\"",
    "\"--\"",
    "\"==\"",
    "\">\"",
    "\"++\"",
    "\"&&\"",
    "\"<=\"",
    "\"!\"",
    "\"-\"",
    "\"+=\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"~\"",
    "\"?\"",
    "\"!=\"",
    "\"/=\"",
    "\"-=\"",
    "\"*=\"",
    "\"%=\"",
    "\">>=\"",
    "\">>>=\"",
    "\">=\"",
    "\"<<=\"",
    "\"<\"",
    "\"^=\"",
    "\"|=\"",
    "\"||\"",
    "\"&=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<NON_ZERO_DIGIT>",
    "<INT_LITERAL>",
    "<CHAR_LITERAL>",
    "<STRING_LITERAL>",
    "<ESC>",
    "<LONG_LITERAL>",
    "<DIGITS>",
    "<EXPONENT>",
    "<SUFFIX>",
    "<DOUBLE_LITERAL>",
    "<ERROR>",
  };

}
